---
name: Rose-DBx-Bouquet
version: 1.00
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: 'Generate a set of Rose::DB::Object- and Rose::HTML::Form-based classes'
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Carp: 0
  Config::IniFiles: 0
  File::Path: 0
  File::Spec: 0
  Getopt::Long: 0
  HTML::Template: 0
  Pod::Usage: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  Rose::DBx::Bouquet:
    file: lib/Rose/DBx/Bouquet.pm
    version: 1.00
  Rose::DBx::Bouquet::Config:
    file: lib/Rose/DBx/Bouquet/Config.pm
    version: 1.00
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
